name: m2release2
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=1.2.0
  - blas=1.0
  - ca-certificates
  - certifi
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - cython=0.29.14
  - dill=0.2.9
  - idna=2.8
  - intel-openmp
  - libedit=3.1
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msgpack-numpy=0.4.4.3
  - msgpack-python=0.5.6
  - ncurses=6.1
  - openjdk=8.0
  - openssl
  - pip=19.3.1
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.6.9
  - readline=7.0
  - requests=2.22.0
  - setuptools=41.6.0
  - six=1.13.0
  - spacy=2.0.11
  - sqlite=3.30.1
  - termcolor=1.1.0
  - thinc=6.11.2
  - tk=8.6.8
  - toolz=0.10.0
  - urllib3=1.24.2
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.8.1
    - cycler==0.10.0
    - cymem==1.31.2
    - cytoolz==0.9.0.1
    - future==0.17.1
    - grpcio==1.25.0
    - h5py==2.8.0
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - matplotlib==2.2.3
    - msgpack==0.6.2
    - multiprocess==0.70.9
    - murmurhash==0.28.0
    - numpy==1.16.4
    - pathlib==1.0.1
    - pathos==0.2.3
    - pillow==6.2.1
    - plac==0.9.6
    - pox==0.2.7
    - ppft==1.6.6.1
    - preshed==1.0.1
    - protobuf==3.10.0
    - pycocotools==2.0.0
    - pyparsing==2.4.5
    - python-dateutil==2.8.1
    - pytz==2019.3
    - regex==2017.4.5
    - tensorboard==1.14.0
    - torch==1.1.0
    - torchvision==0.3.0
    - tqdm==4.32.2
    - ujson==1.35
    - werkzeug==0.16.0
    - wrapt==1.10.11

